setup:
  runner: train_dpdm_base
  CUDA_DEVICES: 0
  n_gpus_per_node: 1
  n_nodes: 1
  node_rank: 0
  master_address: '127.0.0.1'
  master_port: 60202
  omp_n_threads: 64
data:
  path: ""
  name: mimic
  resolution: 1782
  dataloader_params:
    num_workers: 1
  n_classes: None
model:
  denoiser_name: edm
  denoiser_network: song
  ema_rate: .999
  params:
    sigma_data: 0.14
    sigma_min: .02
    sigma_max: 80.
  network:
    z_dim: 1782
    time_dim: 384
    unit_dims: [1024, 384, 384, 384, 1024]
    use_cfg: False
optim:
  optimizer: AdamW
  params:
    lr: 3e-4
    weight_decay: 0.
sampler:
  solver: 'heun'
  discretization: 'edm'
  stochastic: False
  num_steps: 32
  sigma_min: .02
  sigma_max: 80.
  rho: 7.
  guid_scale: None
train:
  seed: 2024
  batch_size: 256
  warmup_steps: 0
  n_epochs: 3000
  check_freq: 5000
  save_freq: 20000
loss: 
  version: edm
  p_mean: -1.2
  p_std: 1.2
  sigma_data: 0.14
  n_noise_samples: 4
  n_classes: None
dp:
  do: True
  max_grad_norm: 1.1
  delta: 1e-5
  epsilon: 10.
  max_physical_batch_size: 1024
  n_splits: 8